name: linting, testing, building

on:
  push:
    branches:
      - ${{ github.ref_name }}
  pull_request:
    branches:
      - develop

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}

      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm install

      - name: Build production project
        run: npm run build:prod

      - name: Linting TypeScript
        run: npm run lint:ts

      - name: Linting CSS
        run: npm run lint:scss

      - name: Unit testing
        run: npm run test:unit